fix(releaser): stop release on fail

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -28,3 +28,9 @@ jobs:
           hooks: goreleaser
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        continue-on-error: false  
+      - name: Abort if semantic release failed
+        if: failure()
+        run: |
+          echo "🚨 Go Semantic Release failed! Aborting..."
+          exit 1
